name: CI

on: [pull_request]

jobs:
  format_prettier:
    name: Format with Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn format:prettier --check

  lint_markdown:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn lint:markdownlint
